theme: just-the-docs

logo: "/assets/img/logo.png"
favicon_ico: "/assets/img/favicon.png"

aux_links:
  "Github":
    - "https://github.com/orion-services"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2024 <a href='https://orion-services.dev'>Orion Services</a>. Distributed by Apache 2.0 license."